/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EnterDocs: typeof import('./src/components/EnterDocs.vue')['default']
    FloatingQA: typeof import('./src/components/FloatingQA.vue')['default']
  }
}
